### ISSUE TITLE
Please add scale option to image cropping

### ISSUE THREAD

**Issue by hembachrterran** [leopq/capacitor-resources#6]
I tried to use this code to generate a splash screen, the logo placed in the middle of the 2732x2732 px, quite small compared to the space around it, and even so, it cut out parts of it in the generated resolutions.

**Comment by leonardoquevedox** [comment]
@hembachrterran Added --transform-splash thanks to latest community PRs, wich will probably solve your issue.  

You can try it with:

`npm install capacitor-resources@latest && npm run capacitor-resources --transform-splash cover` 
or 
`npm install capacitor-resources@latest && npm run capacitor-resources --transform-splash crop`

And check which works out best for you ;)
